<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>foldingStartMarker</key>
	<string>&lt;[a-z]|\#\ \-\-\-</string>
	<key>foldingStopMarker</key>
	<string>&lt;\/[a-z]|\#\ \-\=\-</string>
	<key>name</key>
	<string>PowerMTA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Section Seperators</string>
			<key>match</key>
			<string>(#\s--------------------------------------------------------------)</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>To Do</string>
			<key>match</key>
			<string>(#\sTODO: .*)</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Important Notices</string>
			<key>match</key>
			<string>(#\sIMPORTANT: .*)</string>
			<key>name</key>
			<string>cem.important</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>(#.*)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Opening Blocks</string>
			<key>match</key>
			<string>((&lt;.*)\s(.*)(&gt;))</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Closing Blocks</string>
			<key>match</key>
			<string>(&lt;\/.*&gt;)</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Include Directive</string>
			<key>match</key>
			<string>^[\s|\t]*?(include)+?[\s|\t](.*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Directives</string>
			<key>match</key>
			<string>^[\s|\t]*?([a-zA-Z0-9\-])+?[\s|\t](.*)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>pmta.config</string>
	<key>uuid</key>
	<string>97DD5CAA-4EB2-4999-BD1A-E1EFB39CCC78</string>
</dict>
</plist>
